name: "Donet Pack"

on:
  workflow_dispatch:
  pull_request:
  release:
    types: [released, prereleased]

jobs:
  build-it:
    name: Build .NET Repository
    if: ${{github.event.repository.is_template == false}}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{github.token}}
      GH_REPO_URL: https://github.com/${{github.repository}}
      GH_REPO_GIT_URL: ${{github.repositoryUrl}}
      GH_REPO_DEFAULT_BRANCH: ${{github.event.repository.default_branch}}
    
    steps:
      - name: Full Repository Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-tags: true
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      - name: Build & Package
        id: run
        run: |
          dotnet pack --configuration Release | tee output.log
          last_line=$(tail -n 1 output.log | sed 's/^[   ]*//;s/[    ]*$//')
          echo "LASTLINE=$last_line" >> $GITHUB_OUTPUT
        
      - uses: actions/github-script@v7
        id: attain-fileinfo
        with:
          script: |
            const fs = require('fs');
            core.setOutput("OutputDir", `${{steps.run.outputs.LASTLINE}}`);

      - uses: actions/upload-artifact@v4
        if: ${{steps.attain-fileinfo.outputs.OutputDir != ''}}
        with:
          name: NUPKG
          path: ${{steps.attain-fileinfo.outputs.OutputDir}}
    
  publish-it:
    name: Publish .NET Results
    needs: build-it
    if: ${{github.event_name == 'release'}}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.ORG_PAT }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4

      - id: attain-file-paths
        run: |
          for file in ./NUPKG/*.nupkg; do
            if [ -e "$file" ]; then
              echo "NUPKG=$file" >> $GITHUB_OUTPUT
              break
            fi
          done
        
      - name: Publish to Github 
        if: ${{steps.attain-file-paths.outputs.NUPKG != ''}}
        run: |
          gh release upload ${{ github.event.release.tag_name }} "${{steps.attain-file-paths.outputs.NUPKG}}"

      - name: Publish to Nuget
        if: ${{steps.attain-file-paths.outputs.NUPKG != '' && github.event.release.prerelease == false}}
        run: |
          dotnet nuget push "${{steps.attain-file-paths.outputs.NUPKG}}" --api-key ${{ secrets.NUGET_API_TOKEN }} --source https://api.nuget.org/v3/index.json
    